### ISSUE TITLE
Cannot use wildcards to specify file names in the command prompt of Windows

### ISSUE THREAD

**Issue by tos-kamiya** [tos-kamiya/dendro_text#1]
Running `dendro_text` at the Windows command prompt and trying to specify files with a wildcard, such as `*.txt`, it will stop with the following error.

```sh
C:\Users\toshihiro\tmp>dendro_text *.txt
Traceback (most recent call last):
  File "C:\Users\toshihiro\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\toshihiro\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\toshihiro\AppData\Local\Programs\Python\Python310\Scripts\dendro_text.exe\__main__.py", line 7, in <module>
  File "C:\Users\toshihiro\AppData\Local\Programs\Python\Python310\lib\site-packages\dendro_text\main.py", line 309, in main
    docs = [read_doc(f) for f in files]
  File "C:\Users\toshihiro\AppData\Local\Programs\Python\Python310\lib\site-packages\dendro_text\main.py", line 309, in <listcomp>
    docs = [read_doc(f) for f in files]
  File "C:\Users\toshihiro\AppData\Local\Programs\Python\Python310\lib\site-packages\dendro_text\main.py", line 285, in read_doc
    with open(f, "r") as inp:
OSError: [Errno 22] Invalid argument: '*.txt'

C:\Users\toshihiro\tmp>dendro_text --version
dendro_text 1.6.0
```

**Comment by tos-kamiya** [comment]
In Windows, wildcard expansion is supposed to be done on the command side, so using Powershell's command substitution seems to be the correct way to go.
,
In the example above, the following would specify files matching a wildcard `*.txt`, on the PowerShell:

```sh
dendro_text $(ls *.txt)
```

**Comment by tos-kamiya** [comment]
Windows-spec wildcard has been supported in v1.7.0.
